INSERT INTO PELICULA(PELICULA_ID, NOMBRE, PRECIO, GENERO, DURACION, CLASIFICACION, TIPO_SERVICIO) 	VALUES(PELICULA_SEQ.NEXTVAL, "TITANIC", 80, "ROMACE",195, "PG-13", "PAQUETERIA");  
INSERT INTO PELICULA(PELICULA_ID, NOMBRE, PRECIO, GENERO, DURACION, CLASIFICACION) 					VALUES(PELICULA_SEQ.NEXTVAL, "HARRY POTTER-CALIZ_FUEGO", 200, "FANTASIA",157, "PG-13");  
INSERT INTO PELICULA(PELICULA_ID, NOMBRE, PRECIO, GENERO, DURACION, CLASIFICACION, TIPO_SERVICIO) 	VALUES(PELICULA_SEQ.NEXTVAL, "TIEMPOS MODERNOS", 70, "COMEDIA",87, "B", "PAQUETERIA");

INSERT INTO ALBUM(ALBUM_ID, NOMBRE, PRECIO, TIPO_SERVICIO, DISQURA, ARTISTA, ANIO) 					VALUES(ALBUM_SEQ.NEXTVAL, "AL FINAL DE ESTE VIAJE", 70, "PAQUETERIA","ESTUDIOS SONOLAND", "SILVIO RODRIGUEZ",1978);  
INSERT INTO ALBUM(ALBUM_ID, NOMBRE, PRECIO, DISQUERA, ARTISTA, ANIO)				 				VALUES(ALBUM_SEQ.NEXTVAL, "THE DARK SIDE OF THE MOON", 150,"ABBEY ROAD STUDIOS", "PINK FLOYD",1973);  
INSERT INTO ALBUM(ALBUM_ID, NOMBRE, PRECIO, DISQUERA, ARTISTA, ANIO)				 				VALUES(ALBUM_SEQ.NEXTVAL, "NEVERMIND", 180,"VAN NUYS", "NIRVANA",1991);

INSERT INTO JUEGO(JUEGO_ID, NOMBRE, PRECIO, TIPO_SERVICIO) 											VALUES(JUEGO_SEQ.NEXTVAL, "CALL OF DUTY", 3000,"PAQUETERIA");
INSERT INTO JUEGO(JUEGO_ID, NOMBRE, PRECIO, TIPO_SERVICIO, CONSOLA) 								VALUES(JUEGO_SEQ.NEXTVAL, "SUPER MARIO BROS 3", 500,"PAQUETERIA", "NINTENDO");
INSERT INTO JUEGO(JUEGO_ID, NOMBRE, PRECIO, CONSOLA) 												VALUES(JUEGO_SEQ.NEXTVAL, "AGED OF EMPIRES", 1000, "WINDOWS");

INSERT INTO CLIENTE(CLIENTE_ID, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, PASSWORD, TELEFONO, FORMA_PAGO_ID, CORREO, DIRECCION_ID, ORDEN_COMPRA_ID) VALUES("JUAN01", "JUAN", "PEREZ", "HERNANDEZ", "YOMERENGUES", "5545566778", FORMA_PAGO_SEQ.NEXTVAL, "JUANITO@GMAIL.COM", DIRECCION_SEQ.NEXTVAL, ORDEN_COMPRA.NEXTVAL);
INSERT INTO DIRECCION(DIRECCION_ID, CALLE, NUMERO_EXT, COLONIA, CODIGO POSTAL, DELEGACION) VALUES(DIRECCION_SEQ.CURRVAL, "LAURO AGUIRRE", "17", "MINAS COYOTE", "53543", "NAUCALPAN");
INSERT INTO ORDEN_COMPRA(ORDEN_COMPRA_ID, TIPO_SERVICIO, PRODUCTO_ID, FACTURA_ID) VALUES(ORDEN_COMPRA.CURRVAL, "STREAMING", PRODUCTO.NEXTVAL, FACTURA_SEQ.NEXTVAL);
INSERT INTO PRODUCTO(PRODUCTO_ID, TIPO, CANTIDAD, PRECIO) VALUES(PRODUCTO.CURRVAL, "PELICULA", 1, 80);
INSERT INTO FACTURA(FACTURA_ID, IVA, MONTO, FECHA) VALUES(FACTURA_SEQ.CURRVAL, 8, 80, TO_DATE('2018/02/24','YYYY/MM/DD' );


INSERT INTO CLIENTE(CLIENTE_ID, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, PASSWORD, TELEFONO, FORMA_PAGO_ID, CORREO, DIRECCION_ID, ORDEN_COMPRA_ID) VALUES("ARMANDO101", "ARMANDO", "RIVERA", "NEGRETE", "ARMRIVNEG", "5524568076", FORMA_PAGO_SEQ.NEXTVAL, "RIVERA.ARMANDO@GMAIL.COM", DIRECCION_SEQ.NEXTVAL, ORDEN_COMPRA.NEXTVAL);
INSERT INTO DIRECCION(DIRECCION_ID, CALLE, NUMERO_EXT, COLONIA, CODIGO POSTAL, DELEGACION) VALUES(DIRECCION_SEQ.CURRVAL, "CARRILLO PUERTO", "37", "SAN RAFAEL", "57572", "NAUCALPAN");
INSERT INTO ORDEN_COMPRA(ORDEN_COMPRA_ID, TIPO_SERVICIO, PRODUCTO_ID, FACTURA_ID) VALUES(ORDEN_COMPRA.CURRVAL, "STREAMING", PRODUCTO.NEXTVAL, FACTURA_SEQ.NEXTVAL);
INSERT INTO PRODUCTO(PRODUCTO_ID, TIPO, CANTIDAD, PRECIO) VALUES(PRODUCTO.CURRVAL, "ALBUM", 1, 70);
INSERT INTO FACTURA(FACTURA_ID, MONTO, FECHA) VALUES(FACTURA_SEQ.CURRVAL, 80, TO_DATE('2018/03/24','YYYY/MM/DD' );


INSERT INTO CLIENTE(CLIENTE_ID, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, PASSWORD, TELEFONO, FORMA_PAGO_ID, CORREO, DIRECCION_ID, ORDEN_COMPRA_ID) VALUES("DAVID300", "DAVID", "SILVA", "LOPEZ", "DASILO", "5583465579", FORMA_PAGO_SEQ.NEXTVAL, "DAVID_SILVA@GMAIL.COM", DIRECCION_SEQ.NEXTVAL, ORDEN_COMPRA.NEXTVAL);
INSERT INTO DIRECCION(DIRECCION_ID, CALLE, NUMERO_EXT, COLONIA, CODIGO POSTAL, DELEGACION) VALUES(DIRECCION_SEQ.CURRVAL, "LAURO AGUIRRE", "17", "MINAS COYOTE", "53543", "NAUCALPAN");
INSERT INTO ORDEN_COMPRA(ORDEN_COMPRA_ID, TIPO_SERVICIO, PRODUCTO_ID, FACTURA_ID) VALUES(ORDEN_COMPRA.CURRVAL, "PAQUETERIA", PRODUCTO.NEXTVAL, FACTURA_SEQ.NEXTVAL);
INSERT INTO PRODUCTO(PRODUCTO_ID, TIPO, CANTIDAD, PRECIO) VALUES(PRODUCTO.CURRVAL, "JUEGO", 1, 3000);
INSERT INTO FACTURA(FACTURA_ID, IVA, MONTO, FECHA) VALUES(FACTURA_SEQ.CURRVAL, 13, 3000, TO_DATE('2018/04/11','YYYY/MM/DD' );
